config/routes.rb
Rails.application.routes.draw do
  get 'contact/new'
  get 'contact/create'
  get 'resume/index'
  get 'project/hoomies'
  get 'project/vegefoods'
  get 'project/catstore'
  get 'contact/index'
  get 'project/index'
  get 'resume/download'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => "home#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters
    helper_method :resource_name, :resource, :devise_mapping, :resource_class


    def resource_name
      :user
    end

    def resource
      @resource ||= User.new
    end

    def resource_class
      User
    end

    def devise_mapping
      @devise_mapping ||= Devise.mappings[:user]
    end
    protected
    def configure_permitted_parameters
        devise_parameter_sanitizer.permit(:account_update, except: [:password], keys: [:firstname, :lastname, :phone, :address])
    end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        @user = User.find_by(email: 'beanjarahoussen@gmail.com')
        @url = 'home'
    end
end

app/controllers/project_controller.rb
class ProjectController < ApplicationController
  def index
    @user = User.find_by(email: 'beanjarahoussen@gmail.com')
    @url = 'project'
  end

  def hoomies
    @user = User.find_by(email: 'beanjarahoussen@gmail.com')
    @url = 'project'
  end

  def vegefoods
    @user = User.find_by(email: 'beanjarahoussen@gmail.com')
    @url = 'project'
  end

  def catstore
    @user = User.find_by(email: 'beanjarahoussen@gmail.com')
    @url = 'project'
  end
end

app/controllers/resume_controller.rb
class ResumeController < ApplicationController
  def index
    @user = User.find_by(email: 'beanjarahoussen@gmail.com')
    @url = 'resume'
  end

  def download
    send_file(
      "#{Rails.root}/public/beanjara.pdf",
      filename: "beanjara.pdf",
      type: "application/pdf"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
    def title_for_page(page_title)
        base_title = "Be Anjara's Portfolio"
        if page_title.empty?
            page_title = base_title
        else
            page_title = page_title
        end
        # page_title.empty? ?  page_title : "#{base_title}"
    end
end

app/helpers/contact_helper.rb
module ContactHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_helper.rb
module ProjectHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/contact/create.html.erb
<h1>Contact#create</h1>
<p>Find me in app/views/contact/create.html.erb</p>

app/views/contact/new.html.erb
<%= render "shared/portfolio_nav"%>
<div class="header-intro theme-bg-primary text-white py-5">
	        <div class="container">
		        <h2 class="page-heading mb-0">Contactez-moi</h2>
		        
    </div><!--//container-->
</div><!--//header-intro-->

 <section class="section py-5">
        <div class="container">
            <div class="row">
		        <div class="contact-intro col-lg-8 mx-lg-auto mb-5 text-center">
			        
			        <img class="profile-small d-inline-block mx-auto rounded-circle mb-3" src="<%= image_url('tryprofil.jpg')%>" alt="">
			        
			        <div class="speech-bubble bg-white p-4 p-lg-5 shadow-sm">
				        <p class="text-left mb-3">
						Je suis un développeur junior full stack spécialisé en Ruby, à la recherche d’un poste stagiaire développeur web junior PHP ou Ruby. Ayant déjà réalisé quelques projets personnels, je cherche de continuité pour solidifier mes compétences en développement web.
			<br>    Souhaitez-vous connaître mes parcours académiques ou de projet que j’ai contribué ? Suivez ces liens  <a href="<%= resume_index_path %>"> Mon parcours </a>  ou <a href="<%= project_index_path %>">Mes projets</a>.
				        <h6 class="font-weight-bold text-center mb-3">Vous pouvez aussi me contactez sur :</h6>
				        
				        <ul class="social-list-color list-inline mb-0">				            
			                <li class="list-inline-item mb-3"><a class="linkedin" href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
			                <li class="list-inline-item mb-3"><a class="github" href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
			                <li class="list-inline-item mb-3"><a class="stack-overflow" href="#"><i class="fab fa-gitlab fa-fw"></i></a></li>
			                <li class="list-inline-item mb-3"><a class="facebook" href="#"><i class="fab fa-facebook-f fa-fw"></i></a></li>
			                <!--<li class="list-inline-item"><a class="instagram" href="#"><i class="fab fa-instagram fa-fw"></i></a></li>-->
			            </ul><!--//social-list-->
			        </div>
			        
		        </div><!--//contact-intro-->
				 <%= form_tag contact_new_path, method: "POST" , class: "contact-form col-lg-8 mx-lg-auto", id:"contact-form" do %>
			        <h3 class="text-center mb-3">Contactez-moi</h3>
			        <div class="form-row">                                                           
		                <div class="form-group col-md-6">
		                    <label class="sr-only" for="cname">Nom</label>
		                    <input type="text" class="form-control" id="cname" name="name" placeholder="Nom" minlength="2" required="" aria-required="true">
		                </div>                    
		                <div class="form-group col-md-6">
		                    <label class="sr-only" for="cemail">Email</label>
		                    <input type="email" class="form-control" id="cemail" name="email" placeholder="Email" required="" aria-required="true">
		                </div>
		                <div class="form-group col-12">
		                    <label class="sr-only" for="cmessage">Message</label>
		                    <textarea class="form-control" id="cmessage" name="message" placeholder="Envoyer-moi un message" rows="10" required="" aria-required="true"></textarea>
		                </div>
		                
						<div class="form-group col-12">
							<%= submit_tag "Envoyer", class: "btn btn-block btn-primary py-2"%>
						</div>                          
		            </div><!--//form-row-->
		        <% end %>
		        
            </div><!--//row-->
        </div><!--//container-->
    </section><!--//section-->

<%= render 'shared/footer'%>

app/views/home/index.html.erb
<%= render 'shared/portfolio_nav' %>
<%= render 'layouts/about'%>
<%= render 'layouts/skill_overview'%>
<%= render 'layouts/project_features'%>
<%= render 'shared/cta'%>
<%= render 'shared/footer'%>

app/views/layouts/_about.html.erb
<div class="header-intro theme-bg-primary text-white py-5">
	<div class="container">
		<div class="profile-teaser media flex-column flex-md-row">
			<!-- <img class="profile-image mb-3 mb-md-0 mr-md-5 ml-md-0 rounded mx-auto" src="assets/images/profile.jpg" alt="">-->
			<img src="<%= image_url("tryprofil.jpg") %>" alt="Image" class="profile-image mb-3 mb-md-0 mr-md-5 ml-md-0 rounded mx-auto">
			<div class="media-body text-center text-md-left">
			<div class="lead">Bonjour, je m'appelle</div>
			<h2 class="mt-0 display-6 font-weight-bold"><%= @user.lastname %> <%= @user.firstname %> </h2>
			<div class="bio mb-3">
					Je suis un développeur junior full stack spécialisé en Ruby, à la recherche d’un poste stagiaire développeur web junior PHP ou Ruby. Ayant déjà réalisé quelques projets personnels, je cherche de continuité pour solidifier mes compétences en développement web.
			<br>    Souhaitez-vous connaître mes parcours académiques ou de projet que j’ai contribué ? Suivez ces liens  <a class="link-on-bg" href="<%= resume_index_path %>"> Mon parcours </a>  ou <a class="link-on-bg" href="<%= project_index_path %>">Mes projets</a>.
				
			</div><!--//bio--> 
			<a class="theme-btn-on-bg btn font-weight-bold theme-btn-cta" href="contact.html">Embauchez-moi</a>
			
			</div><!--//media-body-->
		</div><!--//profile-teaser-->
		
	</div><!--//container-->
</div><!--//header-intro-->

app/views/layouts/_project_features.html.erb
<section class="section-featured-projects py-5">
        <div class="container">
	        <h3 class="section-title font-weight-bold text-center mb-5">Projets</h3>
        
	        <div class="project-cards row mb-5 isotope">
		        <div class="isotope-item col-12 col-lg-4 ruby rails">
					<div class="card rounded-0 border-0 shadow-sm mb-5 mb-lg-0">
						<div class="card-img-container position-relative">
							<img class="card-img-top rounded-0" src="<%= image_url('projects/hoomies1.png')%>" alt="">
							<div class="card-img-overlay overlay-logo text-center">
								<div class="project-logo">
								    <h5 class="card-title font-weight-bold" style="font-size:30px; margin-top:25px;">Hoomies</h5>
                                </div>
							</div>
							<a class="card-img-overlay overlay-content text-left p-lg-4" href="<%= project_hoomies_path %>">
								<h5 class="card-title font-weight-bold" style="margin-bottom:0px;">Hoomies</h5>
							    <p class="card-text">Hoomies est une plateforme digital qui a pour but de relier les propriétaires de biens immobiliers et les locataires ou acheteurs sans passer par une agence immobilière.</p>
							</a>
						</div>
						<div class="card-body pb-0">
							<h4 class="card-title text-truncate text-center mb-0"><a href="<%= project_hoomies_path %>">Vente/Location imobilières</a></h4>
						</div>
						
						<div class="card-footer border-0 text-center bg-white pb-4">
							<ul class="list-inline mb-0 mx-auto">
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">Ruby</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill" >Rails</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">PostgresSQL</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">HTML/CSS</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">OpenStreetMap</span></li>

							</ul>
					    </div>
				    </div><!--//card-->
		        </div>
		        <div class="isotope-item col-12 col-lg-4 php symfony react">
					<div class="card rounded-0 border-0 shadow-sm mb-5 mb-lg-0">
						<div class="card-img-container position-relative">
							<img class="card-img-top rounded-0" src="<%= image_url('projects/vegefoods2.png')%>" alt="">
							<div class="card-img-overlay overlay-logo text-center">
								<div class="project-logo">
								    <h5 class="card-title font-weight-bold" style="font-size:30px; margin-top:25px;">Vegefoods</h5>
                                </div>
							</div>
							<a class="card-img-overlay overlay-content text-left p-lg-4" href="<%= project_vegefoods_path %>">
								<h5 class="card-title font-weight-bold" style="margin-bottom:0px;">Vegefoods Mada</h5>
							    <p class="card-text">Projet personnel en cours de développement, Vegefoods est une application web permettant d’acheter des fruits et de légumes en ligne.</p>
							</a>
						</div>
						<div class="card-body pb-0">
							<h4 class="card-title text-truncate text-center mb-0"><a href="<%= project_vegefoods_path %>">Vente de Fruits et Légumes</a></h4>
						</div>
						
						<div class="card-footer border-0 text-center bg-white pb-4">
							<ul class="list-inline mb-0 mx-auto">
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill" >PHP</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">Symfony 4</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">jQuery</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">MySQL</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">OpenStreetMap</span></li>
							</ul>
					    </div>
				    </div><!--//card-->
		        </div>
		        <div class="isotope-item col-12 col-lg-4 ruby rails">
					<div class="card rounded-0 border-0 shadow-sm mb-5 mb-lg-0">
						<div class="card-img-container position-relative">
							<img class="card-img-top rounded-0" src="<%= image_url('projects/project-3-thumb.jpg')%>" alt="">
							<div class="card-img-overlay overlay-logo text-center">
								<div class="project-logo">
								    <h5 class="card-title font-weight-bold" style="font-size:30px; margin-top:25px;">CatStore</h5>
                                </div>
							</div>
							<a class="card-img-overlay overlay-content text-left p-lg-4" href="<%= project_catstore_path %>">
								<h5 class="card-title font-weight-bold" style="margin-bottom:0px;">CatStore</h5>
							    <p class="card-text">Catstore est une application web que on a développé pour solidifer mes compétences en ruby on rails. C’est une plateforme  de vente des chats en ligne.</p>
							</a>
						</div>
						<div class="card-body pb-0">
							<h4 class="card-title text-truncate text-center mb-0"><a href="<%= project_catstore_path %>">Projet personnel</a></h4>
						</div>
						
						<div class="card-footer border-0 text-center bg-white pb-4">
							<ul class="list-inline mb-0 mx-auto">
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">Ruby</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill" >Rails</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">PostgresSQL</span></li>
						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">Bootstrap</span></li>						        <li class="list-inline-item"><span class="badge badge-secondary badge-pill">Javascript/JQuery</span></li>

							</ul>
					    </div>
				    </div><!--//card-->
		        </div>
			    
	        </div><!--//row-->
	        <div class="text-center">
	            <a class="btn btn-primary" href="<%= project_index_path %>">Tous mes projects</a>
	        </div>
        </div><!--///container-->
        
</section>

app/views/layouts/_skill_overview.html.erb
<style>
    .skills-block-inner {
        height: 304px;
    }
</style>
<section class="skills-section section py-5">
        <div class="container">
	        <h3 class="section-title font-weight-bold text-center mb-3">Compétences</h3>
	        <div class="section-intro mx-auto text-center mb-5 text-secondary">
La réalisation de quelques projets en ruby et php,m’ a permit de maîtriser différents technologies de développement informatique. Ci-dessous, les technologies que j’ai déjà utilisées :			</div>
	        
	        <div class="skills-blocks mx-auto pt-5">
		        <div class="row">
			        <div class="skills-block col-12 col-lg-4 mb-5 mb-3 mb-lg-0">
				        <div class="skills-block-inner bg-white shadow-sm py-4 px-5 position-relative">
					        <h4 class="skills-cat text-center mb-3 mt-5">Frontend</h4>
					        <div class="skills-icon-holder position-absolute d-inline-block rounded-circle text-center">
					            <img class="skills-icon" src="<%= image_url('frontend-icon.svg') %>">
					        </div>
					        <ul class="skills-list list-unstyled text-secondary">
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>Javascript</li>						        
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>AngularJs (Notion)</li>
                                <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>Jquery</li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>Bootstrap</li>
					        </ul>
				        </div><!--//skills-block-inner-->
			        </div><!--//skills-block-->
			        
			        <div class="skills-block col-12 col-lg-4 mb-5 mb-3 mb-lg-0">
				        <div class="skills-block-inner bg-white shadow-sm py-4 px-5 position-relative">
					        <h4 class="skills-cat text-center mb-3 mt-5">Backend</h4>
					        <div class="skills-icon-holder position-absolute d-inline-block rounded-circle text-center">
					           <img class="skills-icon" src="<%= image_url('backend-icon.svg') %>">
					        </div>
					        <ul class="skills-list list-unstyled text-secondary">
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>Ruby/Rails</li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>PHP/Symfony 4</li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>MySql/PostgreSQL</li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>SQLite</li>
					        </ul>
				        </div><!--//skills-block-inner-->
			        </div><!--//skills-block-->
			        
			        <div class="skills-block col-12 col-lg-4">
				        <div class="skills-block-inner bg-white shadow-sm py-4 px-5 position-relative">
					        <h4 class="skills-cat text-center mb-3 mt-5">Autres</h4>
					        <div class="skills-icon-holder position-absolute d-inline-block rounded-circle text-center">
                                <img class="skills-icon" src="<%= image_url('other-skills-icon.svg') %>">   
					        </div>
					        <ul class="skills-list list-unstyled text-secondary">
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i> Git </li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>Wordpress</li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>Doctrine</li>
						        <li class="mb-2"><i class="fas fa-check mr-2 text-primary"></i>OpenStreetMap</li>
					        </ul>
				        </div><!--//skills-block-inner-->
			        </div><!--//skills-block-->
			        
		        </div><!--//row-->
	        </div>
        </div><!--//container-->
</section><!--//skills-section-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>
      <%= title_for_page(yield :title) %>
    </title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    
    <!-- Meta -->
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Be Anjara Houssen's Portfolio">
    <meta name="author" content="Be Anjara Houssen">
  </head>

  <body>
    <div class="site-loader"></div>
    <%= yield %>
  </body>
</html>

app/views/project/index.html.erb
<%= content_for(:title, "Be Anjara's Project") %>
<%= render 'shared/portfolio_nav' %>
<div class="header-intro theme-bg-primary text-white py-5">
    <div class="container">
        <h2 class="page-heading mb-3"> Mes Projets </h2>
        <div class="page-heading-tagline"> Développeur junior fullstack à la recherche d'un stage ou de premier emploie, j'ai déjà participer à 3 différents projets </div>
        
    </div><!--//container-->
</div><!--//header-intro-->

<section class="section pt-5">
    <div class="container">
        <div class="text-center">
            <ul id="filters" class="filters mb-5 mx-auto pl-0">
                <li class="type active" data-filter="*">Tous</li>
                <li class="type" data-filter=".symfony">Symfony</li>
                <li class="type" data-filter=".ruby">Ruby</li>
                <li class="type" data-filter=".php">PHP</li>
                <li class="type" data-filter=".rails">Ruby on Rails</li>
                <li class="type" data-filter=".react">React</li>
            </ul><!--//filters-->
        </div>
        <%= render 'layouts/project_features'%>
    </div><!--//container-->
</section><!--//section-->
<%= render 'shared/cta'%>
<%= render 'shared/footer'%>

app/views/shared/_cta.html.erb
<section class="section-cta py-5 bg-primary text-white">
    <div class="container">
        <div class="text-center">
            <img class="profile-small d-inline-block mx-auto rounded-circle mb-2" src="<%= image_url('tryprofil.jpg')%>" alt="">
        </div>
        <h3 class="section-title font-weight-bold text-center mb-2">Mon profil vous intéresse?</h3>
        <div class="section-intro mx-auto text-center mb-3">
            Vous êtes à la recherche d'un développeur fullstak web spécialisé en Ruby On Rails ou PHP/Symfony 4 pour développer votre application web? Contactez-moi via mon émail  <a class="link-on-bg" href="mailto:<%= @user.email %>"><%= @user.email %></a> ou envoie moi un message via <a class="link-on-bg" href="#"> ce formulaire de contact</a>.
        </div>
        <div class="text-center">
            <a class="theme-btn-on-bg btn" href="#">Contactez-moi</a>
        </div>
    </div><!--//container-->
</section>

app/views/shared/_footer.html.erb
<footer class="footer text-light text-center py-2">
    <small class="copyright">Be Anjara Houssen &copy; 2020</small>
</footer>
    

app/views/shared/_portfolio_nav.html.erb
<header class="header">
	    
    <div class="top-bar theme-bg-primary-darken">
        
        <div class="container-fluid">
        
            <nav class="navbar navbar-expand-lg navbar-dark position-relative">
                
                
                <ul class="social-list list-inline mb-0">
                    <li class="list-inline-item"><a class="text-white" href="#"><i class="fab fa-linkedin-in fa-fw"></i></a></li>
                    <li class="list-inline-item"><a class="text-white" href="#"><i class="fab fa-gitlab fa-fw"></i></a></li>
                    <li class="list-inline-item"><a class="text-white" href="#"><i class="fab fa-github-alt fa-fw"></i></a></li>
                </ul><!--//social-list-->
                

                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navigation" aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse text-uppercase" id="navigation">
                    <ul class="navbar-nav ml-lg-auto">
                        <li class="nav-item <% if @url == 'home'%> active <% end %> mr-lg-3">
                            <a class="nav-link" href="<%= root_path %>">Acceuil</a>
                        </li>
                        <li class="nav-item <% if @url == 'project'%> active <% end %> mr-lg-3">
                            <a class="nav-link" href="<%= project_index_path %>">Projets</a>
                        </li>
                        <li class="nav-item <% if @url == 'resume'%> active <% end %> mr-lg-3">
                            <a class="nav-link" href="<%= resume_index_path %>">CV</a>
                        </li>
                        <li class="nav-item mr-lg-3">
                            <a class="nav-link" href="#">Contact</a>
                        </li>
   
                    </ul>
                    <span id="slide-line"></span>
                </div>
                
                
                
            </nav>
        
        </div><!--//container-->
        
    </div><!--//top-bar-->
</header><!--//header-->